- hosts: localhost
  connection: local 
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/cli-tools.yml
    - include_tasks: tasks/nvim-setup.yml
    # - include_tasks: tasks/fzf-setup.yml
    # - include_tasks: tasks/dotfiles.yml
