- hosts: localhost
  connection: local 
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/pip-setup.yml
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/fonts.yml
    # - import_tasks: tasks/tmux-setup.yml


