- name: Update apt cache and make sure that things are installed
  become: true
  apt:
    update_cache: yes
    pkg:
    - tmux
    - xclip
    - ripgrep
    - fd-find
    - stow
    - fzf
  tags:
    - install
    - cli
    - tools
