---
- name: make sure that things are installed
  ansible.builtin.package:
    name:
      - certbot
      # - tmux
      - xclip
      - ripgrep
      - fd-find
      - stow
      - fzf
    state: latest
  become: yes
  tags:
    - install
    - cli
    - tools
