- name: Install nvim requirements 
  become: true
  apt:
    update_cache: yes
    pkg:
    - build-essential
    - ninja-build
    - gettext
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip
    - curl
    - doxygen 
    - lua5.1

    # - libevent
    - libevent-dev
    - libncurses5-dev
    # - ncurses
    - ncurses-dev
    - bison 
    - pkg-config

  tags:
    - install
    - core
    - neovim

