- name: Install nvim requirements 
  become: true
  apt:
    update_cache: yes
    pkg:
    - ninja-build
    - gettext
    - libtool
    - libtool-bin
    - libpthread-stubs0-dev
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip
    - curl
    - doxygen 
  tags:
    - install
    - core
    - neovim

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "picom","htop", "i3", "python3-pip", "dconf-editor", "nvidia-settings", "moreutils"]
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - install
    - core
