- name: install nodejs with nodesource 
  shell: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  become: yes
  tags:
    - install
    - node

- name: install nodejs 
  shell: sudo apt update && sudo apt-get install -y nodejs
  become: yes
  tags:
    - install
    - node
