- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'dotfiles', 'zsh' ]
  become: yes
    
- name: Set default
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: yes
  tags: *tags_for_zsh_tasks

# - name: Change shell to zsh
#   shell: chsh -s $(which zsh)
#   tags: *tags_for_zsh_tasks
#   become: yes
#   changed_when: false

# - name: Check that the somefile.conf exists
#   stat:
#     path: /home/theprimeagen/.oh-my-zsh
#   register: oh_my_stats
#   tags: *tags_for_zsh_tasks

# - name: Oh-My-Zsh
#   shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
#   tags: *tags_for_zsh_tasks
#   become_user: indeevar

- name: Install syntax-hightlighting
  vars:
    - xdg_data_home: "{{ lookup('env', 'HOME') }}/.local/share"
  ansible.builtin.git:
    repo: 'https://github.com/zdharma/fast-syntax-highlighting'
    dest: "{{ xdg_data_home }}/fast-syntax-highlighting"
    update: yes
  tags: *tags_for_zsh_tasks

- name: Install simpler prompt
  vars:
    - xdg_data_home: "{{ lookup('env', 'HOME') }}/.local/share"
  ansible.builtin.git:
    repo: 'https://github.com/vellankiindeevar/simpler'
    dest: "{{ xdg_data_home }}/simpler"
    update: yes
  tags: *tags_for_zsh_tasks

# - name: Install zsh-autosuggestions
#   ansible.builtin.git:
#     repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
#     dest: "{{ XDG_DATA_HOME }}"
#     update: yes
#     version: master
#   tags: *tags_for_zsh_tasks
