- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'dotfiles', 'zsh' ]
  become: yes
    
- name: Set default
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: yes
  tags: *tags_for_zsh_tasks

- name: Install syntax-hightlighting
  vars:
    - xdg_data_home: "{{ lookup('env', 'HOME') }}/.local/share"
  ansible.builtin.git:
    repo: 'https://github.com/zdharma/fast-syntax-highlighting'
    dest: "{{ xdg_data_home }}/fast-syntax-highlighting"
    update: yes
  tags: *tags_for_zsh_tasks

- name: Install simpler prompt
  vars:
    - xdg_data_home: "{{ lookup('env', 'HOME') }}/.local/share"
  ansible.builtin.git:
    repo: 'https://github.com/vellankiindeevar/simpler'
    dest: "{{ xdg_data_home }}/simpler"
    update: yes
  tags: *tags_for_zsh_tasks

